---
name: build
'on':
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to fetch code (actions/checkout)
    container:
      image: ghcr.io/kamailio/pkg-kamailio-docker:${{ github.ref_name }}-${{ matrix.distribution }}
      volumes:
        - ${{ github.workspace }}:/code
      env:
        DIST: ${{ matrix.distribution }}
        CC: ${{ matrix.compilier }}
    strategy:
      matrix:
        include:
          - distribution: bookworm
            compilier: gcc
          - distribution: bookworm
            compilier: clang
          - distribution: sid
            compilier: gcc
          - distribution: sid
            compilier: clang
    steps:
      - uses: actions/checkout@v4
      - uses: ammaraskar/gcc-problem-matcher@0.2.0
      - name: build
        run: |
          cd /code
          ./test/travis/build_travis.sh
        shell: bash
